---
- name: Install LUPSA on [laptop] hosts
  hosts: laptop
  become: true
  tasks:
    - name: Ensure {{ log_path }} has right permissions
      file:
        path: "{{ log_path }}"
        state: touch
        mode: 0664

    - name: Install LUPSA script and unit file
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      with_items:
        - { src: lupsa.sh.j2, dest: "{{ install_path }}", mode: '0775'}
        - { src: lupsa.service.j2, dest: /etc/systemd/system/lupsa.service, mode: '0644'}

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable the LUPSA service
      systemd:
        name: lupsa
        enabled: yes
        state: restarted
